name: "Chromatic"

on: push

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install dependencies
        run: pnpm i
      - name: Run Chromatic
        id: chromatic_publish
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
  test-storybook:
    name: Storybook Tests
    runs-on: ubuntu-latest
    needs: [chromatic]
    steps:
      - name: Run Storybook tests
        run: yarn test-storybook
        env:
          TARGET_URL: "${{ needs.chromatic.outputs.storybookUrl }}"
